### ISSUE TITLE
Utiliser use strict;

### ISSUE THREAD

**Issue by bpesquet** [oc-courses/javascript-web#2]
Ajouter `use strict;` partout ?
Pour l'instant, il n'est pas utilisé dans le [cours JS précédent](https://openclassrooms.com/courses/apprenez-a-coder-avec-javascript)

**Comment by stuff** [comment]
je le laisserai de coté (en expliquant éventuellement a un endroit son utilité)

comme les IIFE, son utilité tend a disparaitre (es6 etant strict par defaut)
