### ISSUE TITLE
Inclure le code JS dans une IIFE

### ISSUE THREAD

**Issue by bpesquet** [oc-courses/javascript-web#4]
J'hésite à englober systématiquement le code JS dans une IIFE :

```
(function() {
  // the code here is executed once in its own scope
})();
```

Je trouve que ça alourdit le code pour des débutants. Je ne l'ai pas fait pour le précédent cours JS.

**Comment by stuff** [comment]
je préconise de ne pas le faire.

ça lourdit effectivement les exemples ET c'est quelque chose qui tend a disparaitre avec tout ce qui est module commonJS / ES6

**Comment by bpesquet** [comment]
@STuFF Ca confirme mon sentiment. Un grand merci pour tous tes conseils très utiles.
