### ISSUE TITLE
Exercice 1 Chapitre 3 

### ISSUE THREAD

**Issue by catpainkiller** [oc-courses/javascript-web#5]
@bpesquet, merci beaucoup de nous apprendre Javascript et de prendre le temps de décortiquer les bases.

Je m'interroge sur l'exercice 1 du chapitre 3 relatif à la modification de la structure de la page.
Ceci revient-il au même que votre correction : 

```
document.getElementById("contenu").innerHTML += '<p>En voici une ' + 
    '<a href = "https://fr.wikipedia.org/wiki/Liste_des_langages_de_programmation">liste</a>' +
    ' plus complète</p>'; 
```

?

A savoir particulièrement, est-ce plus gourmand en ressources/ temps d'exécution que votre correction ou bien est-ce égal mais moins riche d'un point de vue pédagogique?

Merci encore pour vos cours et les exercices!

**Comment by bpesquet** [comment]
Bonjour,

Oui cela revient au même. La différence en performance est négligeable et serait plutôt à l'avantage de votre solution. Par contre, elle augmente le risque d'erreur : [voir cette remarque](https://openclassrooms.com/courses/creez-des-pages-web-interactives-avec-javascript/modifiez-la-page-web#/id/r-3612596).

Pour ma part, je préfère réserver `innerHTML` à la suppression de tout le contenu d'un noeud et créer les éléments un par un, mais c'est un choix personnel.

Bonne continuation.
