### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ydriss** [oc-courses/javascript-web#7]
/* 
Activité 1
*/

// Liste des liens Web à afficher. Un lien est défini par :
// - son titre
// - son URL
// - son auteur (la personne qui l'a publié)
var listeLiens = [
	{
		titre: "So Foot",
		url: "http://sofoot.com",
		auteur: "yann.usaille"
    },
	{
		titre: "Guide d'autodéfense numérique",
		url: "http://guide.boum.org",
		auteur: "paulochon"
    },
	{
		titre: "L'encyclopédie en ligne Wikipedia",
		url: "http://Wikipedia.org",
		auteur: "annie.zette"
    }
];

// TODO : compléter ce fichier pour ajouter les liens à la page web
var divElt = document.getElementsByTagName("div");
var styleElement = getComputedStyle(divElt);

listeLiens.forEach(function (mot) {
	var pElt = document.createElement("p");
	pElt.textContent = mot.url + "/n Ajouté par " + mot.auteur;
	pElt.style.backgroundColor = "white";

	var aElt = document.createElement("a");
	aElt.href = mot.url;
	aElt.textContent = mot.titre;
	aElt.textContent.style.color = "#428bca";

	pElt.appendChild(aElt);
	divElt.appendChild(pElt);
});

document.body.appendChild(divElt);

**Comment by bpesquet** [comment]
Bonjour, j'espère que vous avez pu terminer le cours depuis cette issue.
Bonne continuation.
